[tool.poetry]
name = "fsvf"
version = "0.1.0"
description = ""
authors = ["Logan Walls <2934282+LoganWalls@users.noreply.github.com>", "Ethan Brooks <ethanabrooks@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.10"
jax = "^0.3.14"
jaxlib = "0.3.10"
gym = {version = "^0.24.1", extras = ["atari"]}
dollar-lambda = "^1.1.3"
tensorflow-gpu = "^2.9.1"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
ipdb = "^0.13.9"
ipython = "^8.4.0"
pre-commit = "^2.19.0"
tomli = "^2.0.1"
tomli-w = "^1.0.0"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
