[tool.poetry]
name = "fsvf"
version = "0.1.0"
description = ""
authors = ["Ethan Brooks <ethanabrooks@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
jaxlib = { extras = ["cuda"], version = "0.3.0" }
gym = "^0.25.1"
gym-minigrid = "^1.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
