[tool.poetry]
name = "ppo"
version = "0.1.0"
description = ""
authors = ["Ethan Brooks <ethanabrooks@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
jaxlib = { extras = ["cuda"], version = "0.3.15" }
jax = "^0.3.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
main = 'ppo:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
