actor_steps: 128
batch_size: 128
clip_param: 0.1
decaying_lr_and_clip_param: true
entropy_coeff: 0.01
env_id: my-env-5x5
gamma: 0.99
lambda_: 0.95
learning_rate: 0.0005
log_frequency: 5
num_agents: 32
num_epochs: 3
num_test_agents: 32
num_test_episodes: 256
save_frequency: 100
seed: 0
total_frames: 500_000
vf_coeff: 0.5
