batch_size: 64
input_dim: 20
learning_rate: 0.0001
num_actions: 5
n_context: 11
n_dim: 5
n_test: 1000
n_train: 10000
n_embd: 768
n_head: 12
n_layer: 12
num_train_steps: 75_000
seed: 0
save_frequency: 1000
test_frequency: 100
