batch_size: 64
gamma: 0.9
input_dim: 20
learning_rate: 0.0001
max_dataset_step: 10_000
num_actions: 5
n_embd: 64
n_head: 4
n_layer: 12
num_generated_examples: 1000
num_train_steps: 75_000
seed: 0
save_frequency: 1000
steps_per_prompt: 100
test_frequency: 100
test_size: 5
