batch_size: 64
dropout_rate: 0.3
gamma: 0.9
learning_rate: 0.0001
max_dataset_step: 10_000
num_actions: 5
num_generated_examples: 1000
num_train_steps: 75_000
seed: 0
steps_per_prompt: 100
test_frequency: 100
test_size: 5
